app:
 build: .
 volumes:
  - .:/app
 ports:
  - '3000:3000'
 links:
  - db           # this tells docker-compose auto-connect to mongodb container

db:
 image: mongo   # this adopts image pull from docker hub
